// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Header: typeof import('./components/Header.vue')['default']
    Main: typeof import('./components/Main.vue')['default']
    MenuView: typeof import('./components/MenuView.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RadialMenu: typeof import('./components/RadialMenu.vue')['default']
    SearchPanel: typeof import('./components/SearchPanel.vue')['default']
    Sidebar: typeof import('./components/Sidebar.vue')['default']
    TimerBar: typeof import('./components/TimerBar.vue')['default']
  }
}

export { }
