export enum NuiEventType {
  IsNuiReady = 'fivepd:nui:isNuiReady',
  Close = 'close',
  Mdt = 'view:mdt',
  MenuView = 'view:menu',
  RadialMenu = 'view:radial_menu',
  TimerBar = 'view:timer_bar',
  MenuUp = 'menu:control_up',
  MenuDown = 'menu:control_down',
  MenuLeft = 'menu:control_left',
  MenuRight = 'menu:control_right',
  MenuSelect = 'menu:control_select',
  UpdateMenuItem = 'menu:update_item',
  LocalizationChange = 'localization:change',
  SendMenuObjects = 'send:menus',
  SendRadialMenuObjects = 'send:radialMenus',
  RadialMenuControl = 'radial_menu:control',
  PlaySound = 'sound:play',
  PlayText = 'sound:playText',
}